apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        command: ["docker-entrypoint.sh"]
        args: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:  
            secretKeyRef:
              name: mongodb-secret
              key: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:  
            secretKeyRef:
              name: mongodb-secret
              key: mongopass
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

